package co.com.ticketing.dynamodb.helper;

import co.com.ticketing.dynamodb.support.DynamoErrorMapper;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbAsyncTable;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient;
import software.amazon.awssdk.enhanced.dynamodb.Expression;
import software.amazon.awssdk.enhanced.dynamodb.Key;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.model.GetItemEnhancedRequest;
import software.amazon.awssdk.enhanced.dynamodb.model.PutItemEnhancedRequest;
import software.amazon.awssdk.enhanced.dynamodb.model.QueryEnhancedRequest;

import java.util.Map;
import java.util.function.Function;

/**
 * Base adapter generated by the Bancolombia scaffold, adapted to map explicitly between domain records and
 * DynamoDB beans and to expose conditional writes and strongly consistent reads.
 *
 * @param <E> domain model
 * @param <V> DynamoDB bean
 */
public abstract class TemplateAdapterOperations<E, V> {

    private final Function<E, V> toDataFn;
    private final Function<V, E> toEntityFn;
    private final DynamoDbAsyncTable<V> table;
    private final TableSchema<V> schema;

    protected TemplateAdapterOperations(DynamoDbEnhancedAsyncClient client, Class<V> dataClass, String tableName,
                                        Function<E, V> toDataFn, Function<V, E> toEntityFn) {
        this.toDataFn = toDataFn;
        this.toEntityFn = toEntityFn;
        this.schema = TableSchema.fromBean(dataClass);
        this.table = client.table(tableName, schema);
    }

    /** Inserts the item only if no item with the same partition key exists. */
    protected Mono<E> create(E model, String partitionKeyAttribute, Function<Throwable, Throwable> onDuplicate) {
        var request = PutItemEnhancedRequest.builder(schema.itemType().rawClass())
                .item(toDataFn.apply(model))
                .conditionExpression(Expression.builder()
                        .expression("attribute_not_exists(#pk)")
                        .expressionNames(Map.of("#pk", partitionKeyAttribute))
                        .build())
                .build();
        return Mono.fromFuture(() -> table.putItem(request))
                .thenReturn(model)
                .onErrorMap(error -> DynamoErrorMapper.isConditionalCheckFailure(error)
                        ? onDuplicate.apply(error)
                        : DynamoErrorMapper.map(error));
    }

    protected Mono<E> getById(String id, boolean consistentRead) {
        var request = GetItemEnhancedRequest.builder()
                .key(Key.builder().partitionValue(id).build())
                .consistentRead(consistentRead)
                .build();
        return Mono.fromFuture(() -> table.getItem(request))
                .map(toEntityFn)
                .onErrorMap(DynamoErrorMapper::map);
    }

    /** Queries a secondary index and returns at most one page (bounded by the request limit). */
    protected Flux<E> queryIndex(String indexName, QueryEnhancedRequest request) {
        return Mono.from(table.index(indexName).query(request))
                .flatMapIterable(page -> page.items())
                .map(toEntityFn)
                .onErrorMap(DynamoErrorMapper::map);
    }

    protected TableSchema<V> schema() {
        return schema;
    }

    protected V toData(E model) {
        return toDataFn.apply(model);
    }
}
