package co.com.ticketing.sqs.listener.helper;

import co.com.ticketing.sqs.listener.config.SQSProperties;
import io.micrometer.core.instrument.MeterRegistry;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import reactor.core.Disposable;
import reactor.core.Disposables;
import reactor.core.publisher.Flux;
import reactor.core.observability.micrometer.Micrometer;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Scheduler;
import reactor.core.scheduler.Schedulers;
import software.amazon.awssdk.services.sqs.SqsAsyncClient;
import software.amazon.awssdk.services.sqs.model.DeleteMessageRequest;
import software.amazon.awssdk.services.sqs.model.Message;
import software.amazon.awssdk.services.sqs.model.ReceiveMessageRequest;

import java.time.Duration;
import java.util.function.Function;

/**
 * Long-polling SQS consumer generated by the scaffold. A message is deleted only after its processor completes
 * successfully; on failure it is left in the queue and becomes visible again after the visibility timeout, so
 * delivery is at-least-once and poison messages end up in the dead-letter queue (redrive policy).
 */
public class SQSListener {

    private static final Logger log = LogManager.getLogger(SQSListener.class);
    private static final Duration POLL_ERROR_BACKOFF = Duration.ofSeconds(1);

    private final SqsAsyncClient client;
    private final SQSProperties properties;
    private final String queueUrl;
    private final Function<Message, Mono<Void>> processor;
    private final MeterRegistry meterRegistry;
    private final Disposable.Composite subscriptions = Disposables.composite();
    private Scheduler scheduler;

    public SQSListener(SqsAsyncClient client, SQSProperties properties, String queueUrl,
                       Function<Message, Mono<Void>> processor, MeterRegistry meterRegistry) {
        this.client = client;
        this.properties = properties;
        this.queueUrl = queueUrl;
        this.processor = processor;
        this.meterRegistry = meterRegistry;
    }

    public SQSListener start() {
        scheduler = Schedulers.newParallel("sqs-" + queueName(), properties.numberOfThreads());
        for (var i = 0; i < properties.numberOfThreads(); i++) {
            subscriptions.add(listenRetryRepeat().subscribeOn(scheduler).subscribe());
        }
        log.info("Listening queue {} with {} pollers", queueUrl, properties.numberOfThreads());
        return this;
    }

    /** Stops polling; in-flight messages that are not deleted will be redelivered by SQS. */
    public void stop() {
        subscriptions.dispose();
        if (scheduler != null) {
            scheduler.dispose();
        }
    }

    private Flux<Void> listenRetryRepeat() {
        return listen()
                .onErrorResume(error -> {
                    log.error("Error polling queue {}", queueUrl, error);
                    return Mono.delay(POLL_ERROR_BACKOFF).then(Mono.empty());
                })
                .repeat();
    }

    Flux<Void> listen() {
        return getMessages()
                .flatMap(this::process, Math.max(1, properties.maxNumberOfMessages()));
    }

    private Mono<Void> process(Message message) {
        return processor.apply(message)
                .name("sqs.message.processing")
                .tag("queue", queueName())
                .tap(Micrometer.metrics(meterRegistry))
                .then(confirm(message))
                .onErrorResume(error -> {
                    log.error("Message {} from {} failed and will be redelivered", message.messageId(), queueUrl, error);
                    return Mono.empty();
                });
    }

    private Mono<Void> confirm(Message message) {
        return Mono.fromCallable(() -> DeleteMessageRequest.builder()
                        .queueUrl(queueUrl)
                        .receiptHandle(message.receiptHandle())
                        .build())
                .flatMap(request -> Mono.fromFuture(() -> client.deleteMessage(request)))
                .then();
    }

    private Flux<Message> getMessages() {
        return Mono.fromCallable(() -> ReceiveMessageRequest.builder()
                        .queueUrl(queueUrl)
                        .maxNumberOfMessages(properties.maxNumberOfMessages())
                        .waitTimeSeconds(properties.waitTimeSeconds())
                        .visibilityTimeout(properties.visibilityTimeoutSeconds())
                        .build())
                .flatMap(request -> Mono.fromFuture(() -> client.receiveMessage(request)))
                .doOnNext(response -> log.debug("{} messages received from {}", response.messages().size(), queueUrl))
                .flatMapMany(response -> Flux.fromIterable(response.messages()));
    }

    private String queueName() {
        return queueUrl.substring(queueUrl.lastIndexOf('/') + 1);
    }
}
